import { Link } from 'react-router-dom'
import { Instagram, Facebook } from 'lucide-react'
import { useCatalog } from '../../contexts/CatalogContext'
export default function Footer() {
  const { settings } = useCatalog()
  return <footer className="bg-gradient-to-br from-[#413416] via-plum to-ink text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 md:grid-cols-4 lg:px-8">
    <div className="md:col-span-2"><p className="mb-3 text-[10px] font-bold uppercase tracking-[.25em] text-sand">Crocheté avec passion à Cotonou</p><h2 className="font-display text-3xl">{settings.shop_name}</h2><p className="mt-2 text-[9px] font-semibold uppercase tracking-[.24em] text-sand">{settings.full_name}</p><p className="mt-4 max-w-md text-sm leading-7 text-white/60">Des pièces en crochet uniques, élégantes et personnalisables, réalisées point après point à la main.</p></div>
    <div><h3 className="text-xs font-bold uppercase tracking-[.18em] text-sand">Explorer</h3><div className="mt-5 grid gap-3 text-sm text-white/70"><Link to="/collections">Collection</Link><Link to="/a-propos">Notre histoire</Link><Link to="/faq">Questions fréquentes</Link><Link to="/livraison-et-retours">Livraison et retours</Link><Link to="/conditions-generales">Conditions générales</Link><Link to="/politique-de-confidentialite">Confidentialité</Link><Link to="/mentions-legales">Mentions légales</Link></div></div>
    <div><h3 className="text-xs font-bold uppercase tracking-[.18em] text-sand">Nous contacter</h3><div className="mt-5 grid gap-3 text-sm text-white/70"><span>{settings.phone}</span><span>{settings.email}</span><span>{settings.address}</span><div className="flex gap-4">{settings.instagram&&<a href={settings.instagram} target="_blank" rel="noreferrer" aria-label="Instagram"><Instagram /></a>}{settings.facebook&&<a href={settings.facebook} target="_blank" rel="noreferrer" aria-label="Facebook"><Facebook /></a>}</div></div></div>
  </div><div className="border-t border-white/10 px-5 py-5 text-center text-xs text-white/45">© 2026 TK SHOP. Tous droits réservés. <span className="mx-2 text-white/20">•</span><a href="https://wa.me/2290157888284" target="_blank" rel="noreferrer" className="font-semibold text-sand transition hover:text-white">Réalisé par Mermouz</a></div></footer>
}
