export const siteConfig = {
  name: 'TK SHOP',
  fullName: 'Taye & Kinde Shop',
  slogan: 'L’élégance crochetée à la main.',
  description: 'TK SHOP imagine des pièces en crochet uniques, élégantes et personnalisables, réalisées point après point à la main pour révéler chaque femme.',
  siteUrl: (typeof import.meta !== 'undefined' && import.meta.env?.VITE_SITE_URL) || 'https://tkshop-crochet.com',
  author: 'TK SHOP - Taye & Kinde',
  whatsapp: '2290100000000',
  phone: '+229 01 00 00 00 00',
  email: 'bonjour@tkshop.com',
  address: 'Cotonou, Bénin',
  country: 'Bénin',
  city: 'Cotonou',
  instagram: 'https://instagram.com',
  facebook: 'https://facebook.com',
  tiktok: 'https://www.tiktok.com/@tkshop',
  currency: 'XOF',
  currencySymbol: 'FCFA',
  delivery: 'Livraison disponible au Bénin et à l’international.',
  deliveryFee: 2500,
  keywords: [
    'TK SHOP',
    'crochet',
    'crochet fait main',
    'crochet d’exception',
    'robes en crochet',
    'ensembles crochet',
    'sacs crochet',
    'artisanat bénin',
    'créations crochet',
    'mode artisanale',
    'crochet moderne',
    'sur-mesure',
    'vêtements crochet Cotonou',
    'Marlène crochet'
  ],
}
