import { Link } from 'react-router-dom'
import { ArrowLeft, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import SEO from '../../components/common/SEO'
import Button from '../../components/common/Button'
import { useCart } from '../../contexts/CartContext'
import { formatCurrency } from '../../utils/formatCurrency'
import InstallAppButton from '../../components/common/InstallAppButton'
export default function CartPage() {
  const { items, updateQuantity, removeItem, clearCart, subtotal, deliveryFee, total, itemCount } = useCart()
  const MobileTopbar = () => <div className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-goldSoft/15 bg-ivory/95 px-4 backdrop-blur-xl md:hidden"><Link to="/collections" className="grid h-10 w-10 place-items-center rounded-full bg-mist" aria-label="Retour à la collection"><ArrowLeft className="h-5 w-5"/></Link><div className="text-center"><h1 className="font-display text-xl">Mon panier</h1><p className="text-[9px] uppercase tracking-wider text-gold">{itemCount} article{itemCount > 1 ? 's' : ''}</p></div><InstallAppButton compact/></div>
  if (!items.length) return <><SEO title="Panier | TK SHOP" /><MobileTopbar/><div className="grid min-h-[calc(100vh-4rem)] place-items-center px-5 text-center md:min-h-[65vh]"><div><div className="mx-auto grid h-20 w-20 place-items-center rounded-[2rem] bg-mist"><ShoppingBag className="h-9 w-9 text-gold"/></div><h2 className="mt-6 font-display text-4xl">Votre panier attend une histoire</h2><p className="mx-auto mt-3 max-w-sm text-black/55">Découvrez nos créations au crochet et choisissez celle qui vous ressemble.</p><Button to="/collections" className="mt-7">Découvrir la collection</Button><div className="mx-auto mt-5 max-w-xs md:hidden"><InstallAppButton/></div></div></div></>
  return <><SEO title="Votre panier | TK SHOP" /><MobileTopbar/><div className="mx-auto max-w-7xl px-4 pb-32 pt-6 md:px-5 md:py-16 lg:px-8"><h1 className="hidden font-display text-5xl md:block">Votre panier</h1><div className="md:mt-10 grid gap-8 lg:grid-cols-[1fr_380px] lg:gap-12"><div className="divide-y divide-goldSoft/15 md:border-y">{items.map(item=><article key={item.lineKey} className="grid grid-cols-[88px_1fr] gap-4 py-5 md:grid-cols-[120px_1fr_auto] md:gap-5 md:py-6"><img src={item.images[0]} alt={item.name} className="h-28 w-full rounded-2xl object-cover md:h-36 md:rounded-none"/><div><Link to={`/collections/${item.slug}`} className="font-display text-lg md:text-xl">{item.name}</Link><p className="mt-2 text-[11px] text-black/55">{[item.size&&`Taille ${item.size}`,item.color].filter(Boolean).join(' · ')}</p>{item.note&&<p className="mt-2 text-xs text-black/50">{item.note}</p>}<div className="mt-4 flex w-fit items-center rounded-full border border-goldSoft/20 bg-white"><button onClick={()=>updateQuantity(item.lineKey,item.quantity-1)} className="p-2.5"><Minus className="h-3 w-3"/></button><span className="w-8 text-center text-xs">{item.quantity}</span><button onClick={()=>updateQuantity(item.lineKey,item.quantity+1)} className="p-2.5"><Plus className="h-3 w-3"/></button></div></div><div className="col-start-2 flex items-end justify-between md:col-start-auto md:flex-col md:items-end"><b className="text-sm text-gold md:text-base">{formatCurrency(item.price*item.quantity)}</b><button onClick={()=>removeItem(item.lineKey)} className="flex items-center gap-1.5 text-[11px] text-black/45 hover:text-red-700"><Trash2 className="h-3.5 w-3.5"/> Supprimer</button></div></article>)}
      <div className="flex justify-between py-5 text-sm"><Link to="/collections" className="font-semibold underline">Continuer mes achats</Link><button onClick={clearCart} className="text-black/50">Vider le panier</button></div></div>
      <aside className="fixed inset-x-0 bottom-0 z-20 rounded-t-[2rem] border-t border-goldSoft/15 bg-ivory/95 p-4 shadow-[0_-15px_45px_rgba(74,56,20,.12)] backdrop-blur-xl md:static md:h-fit md:rounded-[2rem] md:bg-mist md:p-7 md:shadow-none lg:sticky lg:top-28"><h2 className="hidden font-display text-2xl md:block">Résumé</h2><div className="hidden mt-6 gap-4 text-sm md:grid"><div className="flex justify-between"><span>Sous-total</span><span>{formatCurrency(subtotal)}</span></div><div className="flex justify-between"><span>Livraison estimée</span><span>{formatCurrency(deliveryFee)}</span></div></div><div className="mb-3 flex justify-between text-lg font-bold md:mt-5 md:border-t md:pt-5"><span>Total</span><span className="text-gold">{formatCurrency(total)}</span></div><Button to="/commande" className="w-full">Passer la commande</Button><p className="mt-3 hidden text-center text-xs leading-5 text-black/45 md:block">Confirmation et paiement convenus directement sur WhatsApp.</p></aside></div></div></>
}
