import { Link } from 'react-router-dom'
import { Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import SEO from '../../components/common/SEO'
import Button from '../../components/common/Button'
import { useCart } from '../../contexts/CartContext'
import { formatCurrency } from '../../utils/formatCurrency'
export default function CartPage() {
  const { items, updateQuantity, removeItem, clearCart, subtotal, deliveryFee, total } = useCart()
  if (!items.length) return <><SEO title="Panier | Atelier Naya" /><div className="grid min-h-[65vh] place-items-center px-5 text-center"><div><ShoppingBag className="mx-auto h-12 w-12 text-gold"/><h1 className="mt-5 font-display text-4xl">Votre panier attend une histoire</h1><p className="mt-3 text-black/55">Découvrez nos créations et choisissez celle qui vous ressemble.</p><Button to="/collections" className="mt-7">Découvrir la collection</Button></div></div></>
  return <><SEO title="Votre panier | Atelier Naya" /><div className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><h1 className="font-display text-5xl">Votre panier</h1><div className="mt-10 grid gap-12 lg:grid-cols-[1fr_380px]"><div className="divide-y border-y">{items.map(item=><article key={item.lineKey} className="grid grid-cols-[100px_1fr] gap-5 py-6 md:grid-cols-[120px_1fr_auto]"><img src={item.images[0]} alt={item.name} className="h-36 w-full object-cover"/><div><Link to={`/collections/${item.slug}`} className="font-display text-xl">{item.name}</Link><p className="mt-2 text-xs text-black/55">{[item.size&&`Taille ${item.size}`,item.color].filter(Boolean).join(' · ')}</p>{item.note&&<p className="mt-2 text-xs text-black/50">{item.note}</p>}<div className="mt-5 flex w-fit items-center border"><button onClick={()=>updateQuantity(item.lineKey,item.quantity-1)} className="p-2"><Minus className="h-3 w-3"/></button><span className="w-8 text-center text-xs">{item.quantity}</span><button onClick={()=>updateQuantity(item.lineKey,item.quantity+1)} className="p-2"><Plus className="h-3 w-3"/></button></div></div><div className="col-start-2 flex items-end justify-between md:col-start-auto md:flex-col md:items-end"><b>{formatCurrency(item.price*item.quantity)}</b><button onClick={()=>removeItem(item.lineKey)} className="flex items-center gap-2 text-xs text-black/50 hover:text-red-700"><Trash2 className="h-4 w-4"/> Supprimer</button></div></article>)}
      <div className="flex justify-between py-5 text-sm"><Link to="/collections" className="font-semibold underline">Continuer mes achats</Link><button onClick={clearCart} className="text-black/50">Vider le panier</button></div></div>
      <aside className="h-fit bg-mist p-7 lg:sticky lg:top-28"><h2 className="font-display text-2xl">Résumé</h2><div className="mt-6 grid gap-4 text-sm"><div className="flex justify-between"><span>Sous-total</span><span>{formatCurrency(subtotal)}</span></div><div className="flex justify-between"><span>Livraison estimée</span><span>{formatCurrency(deliveryFee)}</span></div><div className="flex justify-between border-t pt-5 text-lg font-bold"><span>Total</span><span>{formatCurrency(total)}</span></div></div><Button to="/commande" className="mt-7 w-full">Passer la commande</Button><p className="mt-4 text-center text-xs leading-5 text-black/45">Confirmation et paiement convenus directement sur WhatsApp.</p></aside></div></div></>
}
