import { useState } from 'react'
import { ChevronLeft, ChevronRight, X, MessageCircle, Mail, MapPin } from 'lucide-react'
import SEO from '../../components/common/SEO'
import Button from '../../components/common/Button'
import Accordion from '../../components/common/Accordion'
import { gallery } from '../../data/gallery'
import { faq } from '../../data/faq'
import { siteConfig } from '../../config/siteConfig'

export function AboutPage(){return <><SEO title="Notre histoire | Marlène Shop"/><section className="grid md:grid-cols-2"><div className="flex items-center bg-gradient-to-br from-mist to-linen p-10 md:p-20"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold">Notre histoire</p><h1 className="mt-5 font-display text-5xl">Créer avec les mains, toucher avec le cœur.</h1><p className="mt-7 leading-8 text-black/60">Marlène Shop est née d’une passion pour les matières, les gestes patients et les vêtements qui ont une âme. Nous mêlons crochet, macramé, corde et textiles tissés dans un langage résolument contemporain.</p></div></div><div className="relative min-h-[560px]"><img src="https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=85" alt="Créatrice dans son atelier" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-rose/30 mix-blend-color"/></div></section><section className="mx-auto max-w-5xl px-5 py-24"><h2 className="font-display text-4xl">Le temps comme matière première</h2><div className="mt-8 columns-1 gap-12 md:columns-2"><p className="mb-6 leading-8 text-black/60">Chaque création commence par une conversation. Nous écoutons une envie, un usage, une silhouette. Viennent ensuite le choix des fibres, l’échantillonnage et les heures de confection.</p><p className="leading-8 text-black/60">Notre engagement : des finitions exigeantes, des matières sélectionnées et une relation transparente du premier échange jusqu’à la livraison.</p></div></section></>}

export function GalleryPage(){const [active,setActive]=useState(null);return <><SEO title="Galerie | Marlène Shop"/><div className="mx-auto max-w-7xl px-5 py-16"><div className="text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-gold">Carnet d’atelier</p><h1 className="mt-4 font-display text-5xl">Galerie de réalisations</h1></div><div className="mt-12 columns-2 gap-4 md:columns-3">{gallery.map((g,i)=><button key={g.id} onClick={()=>setActive(i)} className="group relative mb-4 block w-full overflow-hidden"><img src={g.image} alt={g.title} className={`w-full object-cover ${i%3===0?'aspect-[3/4]':'aspect-square'}`}/><span className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 p-4 pt-12 text-left text-sm text-white opacity-0 transition group-hover:opacity-100">{g.title}</span></button>)}</div></div>{active!==null&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/95 p-5" role="dialog"><button className="absolute right-5 top-5 text-white" onClick={()=>setActive(null)}><X/></button><button className="absolute left-4 text-white" onClick={()=>setActive((active-1+gallery.length)%gallery.length)}><ChevronLeft/></button><img src={gallery[active].image} alt={gallery[active].title} className="max-h-[85vh] max-w-[85vw]"/><button className="absolute right-4 text-white" onClick={()=>setActive((active+1)%gallery.length)}><ChevronRight/></button></div>}</>}

export function ContactPage(){return <><SEO title="Contact | Marlène Shop"/><div className="mx-auto grid max-w-6xl gap-14 px-5 py-20 md:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold">Parlons de votre projet</p><h1 className="mt-4 font-display text-5xl">Une question, une envie ?</h1><p className="mt-6 leading-8 text-black/60">Écrivez-nous. Nous vous répondrons avec plaisir pour imaginer ensemble votre prochaine création.</p><div className="mt-10 grid gap-5 text-sm"><p className="flex gap-3"><MessageCircle className="text-gold"/>{siteConfig.phone}</p><p className="flex gap-3"><Mail className="text-gold"/>{siteConfig.email}</p><p className="flex gap-3"><MapPin className="text-gold"/>{siteConfig.address}</p></div></div><form onSubmit={e=>e.preventDefault()} className="grid gap-4">{['Nom','E-mail','Téléphone','Sujet'].map(x=><label key={x} className="text-sm font-semibold">{x}<input className="mt-2 w-full border border-black/20 px-4 py-3"/></label>)}<label className="text-sm font-semibold">Message<textarea rows="5" className="mt-2 w-full resize-none border border-black/20 px-4 py-3"/></label><Button type="submit">Envoyer le message</Button></form></div></>}
export function FaqPage(){return <><SEO title="Questions fréquentes | Marlène Shop"/><div className="mx-auto max-w-3xl px-5 py-20"><h1 className="mb-10 text-center font-display text-5xl">Questions fréquentes</h1><Accordion items={faq}/></div></>}
export function ConfirmationPage(){return <><SEO title="Commande transmise | Marlène Shop"/><div className="grid min-h-[65vh] place-items-center px-5 text-center"><div><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-linen"><MessageCircle/></div><h1 className="mt-6 font-display text-4xl">Votre demande est prête</h1><p className="mx-auto mt-4 max-w-lg leading-7 text-black/55">Votre commande a été ouverte dans WhatsApp. Envoyez le message pour que l’atelier puisse la confirmer avec vous.</p><Button to="/" className="mt-7">Retour à l’accueil</Button></div></div></>}
export function LegalPage({title}){return <><SEO title={`${title} | Marlène Shop`}/><article className="mx-auto max-w-3xl px-5 py-20"><h1 className="font-display text-5xl">{title}</h1><p className="mt-8 leading-8 text-black/60">Cette page présente les informations de référence de Marlène Shop. Les modalités définitives seront mises à jour avant l’ouverture commerciale du service.</p><h2 className="mt-10 font-display text-2xl">Principes généraux</h2><p className="mt-4 leading-8 text-black/60">Les commandes sont confirmées après échange avec l’atelier. Les délais dépendent du modèle, des options de personnalisation et de la destination de livraison.</p></article></>}
