import { useState } from 'react'
import { Navigate, Link, useNavigate, useParams } from 'react-router-dom'
import { Eye, EyeOff, Plus, Search, MoreHorizontal, ArrowUpRight, Package, ShoppingBag, Clock, Banknote } from 'lucide-react'
import { useAdminAuth } from '../../contexts/AdminAuthContext'
import { products } from '../../data/products'
import { orders } from '../../data/orders'
import { categories } from '../../data/categories'
import { gallery } from '../../data/gallery'
import { testimonials } from '../../data/testimonials'
import { formatCurrency } from '../../utils/formatCurrency'
import Button from '../../components/common/Button'
import SEO from '../../components/common/SEO'

export function ProtectedAdminRoute({children}){const {isAuthenticated}=useAdminAuth();return isAuthenticated?children:<Navigate to="/admin/connexion" replace/>}
export function LoginPage(){const [show,setShow]=useState(false);const {login}=useAdminAuth();const navigate=useNavigate();const submit=e=>{e.preventDefault();login();navigate('/admin')};return <><SEO title="Connexion administration | Marlène Shop"/><div className="relative grid min-h-screen place-items-center overflow-hidden bg-gradient-to-br from-[#fff1f7] via-[#ffddeb] to-[#f7b9d2] p-5 dark:from-[#240d19] dark:via-[#45152d] dark:to-[#6f2048]"><div className="absolute -left-24 top-10 h-80 w-80 rounded-full bg-[#ff78ac]/25 blur-3xl"/><div className="absolute -right-24 bottom-10 h-96 w-96 rounded-full bg-white/35 blur-3xl"/><form onSubmit={submit} className="relative w-full max-w-md rounded-[2rem] border border-white/60 bg-white/85 p-8 shadow-[0_30px_90px_rgba(104,25,59,.18)] backdrop-blur-xl dark:border-white/10 dark:bg-[#2f1021]/90"><div className="text-center"><div className="mx-auto mb-5 grid h-16 w-16 place-items-center rounded-2xl bg-gradient-to-br from-[#ff9fc3] to-[#e84f8a] font-display text-2xl text-white shadow-lg">M</div><p className="text-[10px] font-bold uppercase tracking-[.25em] text-gold">Espace privé</p><h1 className="mt-2 font-display text-3xl">Marlène Shop</h1><p className="mt-2 text-sm text-black/50">Connexion à l’administration</p></div><label className="mt-8 block text-sm font-semibold">E-mail<input type="email" required defaultValue="admin@marleneshop.com" className="mt-2 w-full rounded-2xl border border-[#efcad8] bg-white px-4 py-3 outline-none focus:border-gold"/></label><label className="mt-5 block text-sm font-semibold">Mot de passe<div className="relative mt-2"><input type={show?'text':'password'} required defaultValue="marlene-shop" className="w-full rounded-2xl border border-[#efcad8] bg-white px-4 py-3 pr-12 outline-none focus:border-gold"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-3 text-gold">{show?<EyeOff/>:<Eye/>}</button></div></label><div className="my-5 flex justify-between text-xs"><label className="flex items-center gap-2"><input type="checkbox"/> Se souvenir de moi</label><button type="button" className="font-semibold text-gold">Mot de passe oublié</button></div><Button type="submit" className="w-full">Se connecter</Button><Link to="/" className="mt-5 block text-center text-xs text-black/50 hover:text-gold">Retour au site public</Link></form></div></>}
const Title=({children,action})=><div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-gold">Gestion de l’atelier</p><h1 className="mt-1 font-display text-3xl sm:text-4xl">{children}</h1><p className="mt-2 text-sm text-black/45">Pilotez votre activité et vos créations en toute simplicité.</p></div>{action}</div>
const Status=({children})=><span className={`inline-flex rounded-full px-3 py-1.5 text-[10px] font-bold ${children==='Livrée'||children==='Disponible'?'bg-emerald-100 text-emerald-800':children==='Nouvelle'?'bg-[#ffe1ec] text-[#b82860]':'bg-[#eee7ff] text-[#6842a0]'}`}>{children}</span>
export function DashboardPage(){return <><Title>Tableau de bord</Title><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[Package,'Produits','15','+3 créations crochet'],[ShoppingBag,'Commandes','38','+12% ce mois'],[Clock,'En attente','7','À traiter'],[Banknote,'CA estimé','1,2 M FCFA','+18% ce mois']].map(([Icon,label,value,note],index)=><div key={label} className="group relative overflow-hidden bg-white p-5"><div className="absolute -right-8 -top-8 h-24 w-24 rounded-full bg-[#ffd6e6] transition group-hover:scale-125 dark:bg-white/5"/><div className="relative flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#fff0f6] text-gold dark:bg-white/10"><Icon className="h-5 w-5"/></span><span className="text-[10px] font-bold text-gold">{index===2?'Prioritaire':'En hausse'}</span></div><p className="relative mt-5 text-xs text-black/45">{label}</p><b className="relative mt-1 block text-2xl">{value}</b><p className="relative mt-2 text-[10px] text-black/40">{note}</p></div>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-[1.4fr_1fr]"><div className="bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-gold">Performance</p><h2 className="mt-1 font-display text-xl">Évolution des commandes</h2></div><span className="rounded-full bg-mist px-3 py-2 text-[10px]">7 derniers mois</span></div><div className="mt-10 flex h-48 items-end gap-4">{[42,55,38,75,60,90,72].map((h,i)=><div key={i} className="flex-1 rounded-t-xl bg-gradient-to-t from-[#e84f8a] to-[#ffb3cf] transition hover:brightness-105" style={{height:`${h}%`}}/>)}</div></div><div className="bg-white p-6"><p className="text-[10px] font-bold uppercase tracking-wider text-gold">Catalogue</p><h2 className="mt-1 font-display text-xl">Répartition des catégories</h2><div className="mt-6 grid gap-4">{categories.slice(0,5).map((c,i)=><div key={c.slug}><div className="mb-1.5 flex justify-between text-xs"><span>{c.name}</span><b>{25-i*3}%</b></div><div className="h-2.5 overflow-hidden rounded-full bg-mist"><div className="h-full rounded-full bg-gradient-to-r from-[#e84f8a] to-[#ff9fc3]" style={{width:`${25-i*3}%`}}/></div></div>)}</div></div></div><div className="mt-6 bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-wider text-gold">À suivre</p><h2 className="mt-1 font-display text-xl">Commandes récentes</h2></div><Link to="/admin/commandes" className="text-xs font-semibold text-gold">Voir toutes</Link></div><OrderTable/></div></>}
function OrderTable(){return <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b text-xs text-black/40"><tr>{['Référence','Cliente','Ville','Montant','Statut','Date',''].map(x=><th key={x} className="pb-3 font-medium">{x}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id} className="border-b"><td className="py-4 font-bold">{o.id}</td><td>{o.customer}</td><td>{o.city}</td><td>{formatCurrency(o.amount)}</td><td><Status>{o.status}</Status></td><td>{o.date}</td><td><Link to={`/admin/commandes/${o.id}`}><ArrowUpRight className="h-4 w-4"/></Link></td></tr>)}</tbody></table></div>}
export function ProductsAdmin(){return <><Title action={<Button to="/admin/produits/nouveau"><Plus className="h-4 w-4"/>Ajouter une création</Button>}>Produits</Title><div className="bg-white p-5"><div className="mb-5 flex w-fit gap-2 border px-4 py-2"><Search className="h-4 w-4"/><input placeholder="Rechercher" className="outline-none"/></div><div className="overflow-x-auto"><table className="w-full min-w-[750px] text-left text-sm"><tbody>{products.map(p=><tr key={p.id} className="border-t"><td className="py-3"><img src={p.images[0]} alt="" className="h-12 w-10 object-cover"/></td><td><b>{p.name}</b></td><td>{p.category}</td><td>{formatCurrency(p.price)}</td><td><Status>{p.stockStatus}</Status></td><td><Link to={`/admin/produits/${p.id}/modifier`}><MoreHorizontal/></Link></td></tr>)}</tbody></table></div></div></>}
export function ProductFormPage(){const {id}=useParams();const product=products.find(p=>p.id===Number(id));return <><Title>{product?'Modifier la création':'Nouvelle création'}</Title><form onSubmit={e=>e.preventDefault()} className="grid gap-6 lg:grid-cols-[1fr_320px]"><div className="grid gap-5 bg-white p-6"><label className="text-sm font-semibold">Nom<input defaultValue={product?.name} className="mt-2 w-full border px-4 py-3"/></label><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Catégorie<select defaultValue={product?.categorySlug} className="mt-2 w-full border bg-white px-4 py-3">{categories.map(c=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select></label><label className="text-sm font-semibold">Prix<input type="number" defaultValue={product?.price} className="mt-2 w-full border px-4 py-3"/></label></div><label className="text-sm font-semibold">Description courte<textarea rows="3" defaultValue={product?.shortDescription} className="mt-2 w-full border px-4 py-3"/></label><label className="text-sm font-semibold">Description complète<textarea rows="7" defaultValue={product?.description} className="mt-2 w-full border px-4 py-3"/></label><Button>Enregistrer la création</Button></div><aside className="h-fit bg-white p-6"><h2 className="font-display text-xl">Image principale</h2><div className="mt-4 grid aspect-square place-items-center border-2 border-dashed bg-mist text-center text-sm text-black/40">{product?<img src={product.images[0]} className="h-full w-full object-cover"/>:'Déposez une image ici'}</div><div className="mt-5 grid gap-3 text-sm">{['Création personnalisable','Mise en avant','Nouveauté'].map(x=><label key={x}><input type="checkbox" defaultChecked/> {x}</label>)}</div></aside></form></>}
export function OrdersAdmin(){return <><Title>Commandes</Title><div className="bg-white p-6"><OrderTable/></div></>}
export function OrderDetail(){const {id}=useParams();const order=orders.find(o=>o.id===id);return <><Title>Commande {id}</Title><div className="grid gap-6 lg:grid-cols-3"><div className="bg-white p-6 lg:col-span-2"><h2 className="font-display text-xl">Détails de la commande</h2><div className="mt-6 border-y py-5"><b>Robe Marlène Élégance</b><p className="text-sm text-black/50">Taille M · Beige · Quantité 1</p></div><div className="mt-5 flex justify-between text-lg font-bold"><span>Total</span><span>{formatCurrency(order?.amount||0)}</span></div></div><aside className="bg-white p-6"><h2 className="font-display text-xl">Cliente</h2><div className="mt-5 grid gap-2 text-sm"><b>{order?.customer}</b><span>{order?.phone}</span><span>{order?.city}</span><Status>{order?.status}</Status></div><Button className="mt-6 w-full">Ouvrir WhatsApp</Button></aside></div></>}
export function SimpleAdminPage({title,type}){const data=type==='gallery'?gallery:type==='testimonials'?testimonials:categories;return <><Title action={<Button><Plus className="h-4 w-4"/>Ajouter</Button>}>{title}</Title><div className="grid gap-4 md:grid-cols-3">{data.map((x,i)=><div key={x.id||x.slug||x.name} className="bg-white p-5">{x.image&&<img src={x.image} alt="" className="mb-4 h-36 w-full object-cover"/>}<b>{x.title||x.name||`Élément ${i+1}`}</b><p className="mt-2 line-clamp-2 text-sm text-black/50">{x.text||x.category||'Contenu administrable'}</p></div>)}</div></>}
